### ISSUE TITLE
[Feature Request] Action Type: HP Loss

### ISSUE THREAD

**Issue by harrisog** [hanna-greaves/Token-Says#120]
It would be amazing if token sayings were able to trigger off of negative adjustments to the token's Bar 1 attribute. This would really not be Target Reacts "territory" because that module is both system and submod-specific (midiqol), is neither globally configurable nor im/exportable, and has not been updated to support the current version.

**Comment by napolitanod** [comment]
This is an interesting thought, to use the bars - I will research into it to see what is available in the Foundry base code to support this - I need to get my modules ready for the next Foundry release so it will take time before I can get to this.

**Comment by harrisog** [comment]
That's excellent to hear. If you do get around to implementing something along these lines, I would suggest something like two new Action Types (for Bar 1 and Bar 2) with four suboptions: increase, decrease, ==0, and ==max.

**Comment by hanna-greaves** [comment]
hey @napolitanod 👋 thanks so much for your work on this module, its great 🙏 

I was really interested in having the HP loss/gain feature available in my foundry game so I made some changes locally and have something working using the `updateActor` hook.

I'm happy to clean up the change and create a PR if you're open to it? 🙂

**Comment by napolitanod** [comment]
hi @hanna-greaves - I can field a PR, though haven't done it before so may need help walking through. I am looking for somebody to take over ownership of this module. Any interest? I have no time. My concern with PR in the past is that if a person adds functionality and then bails, I feel as if I am left on the hook to maintain it when future bugs are reported against it, whether due to system or foundry functional / api changes

**Comment by napolitanod** [comment]
@hanna-greaves Im good just signing over. Anything waiting on me re review or merging is going to be delayed for some time. I think I have to make a request to foundry staff but will get that in motion.

I don't think there's much complexity in the module but I can answer questions if you don't mind the delay. Historically some of it is built in passing comment objects but there may not be more robust hooks to use for things like dnd5e. 

The biggest gotcha that I can think of is that originally a saying could be either text or audio.  Now it can be both. I never migrated data into the new Json structure so you'll see some janky legacy handling for routing values for handling the old structure.

**Comment by hanna-greaves** [comment]
@napolitanod sorry for the delay, that sounds good to me, feel free to hand everything over whenever you're ready :) give me a shout if there's any additional info you need from me 🙂

**Comment by napolitanod** [comment]
@hanna-greaves do you have a discord account that we can connect over? I am at dnapolitano and I am on the FoundryVTT server. If you can connect with me there I can share with you the instructions from Foundry staff on how to request ownership. The request has to come from you :)

**Comment by hanna-greaves** [comment]
@harrisog this feature has been merged in the latest release
