### ISSUE TITLE
[Update Request] Any plans for a v12 release?

### ISSUE THREAD

**Issue by Drag0nF** [hanna-greaves/Token-Says#140]

**Comment by hanna-greaves** [comment]
Hi @Drag0nF, yes I am planning to work on that this weekend, sorry for the delay 🙏

**Comment by Armandeus66** [comment]
Thank you for the update!

**Comment by hanna-greaves** [comment]
No problem @Armandeus66 ! @Drag0nF the new release has just been published on Foundry, please let me know if you have any issues
