### ISSUE TITLE
[Bug] [PF2E] Takes Damage not working

### ISSUE THREAD

**Issue by harrisog** [hanna-greaves/Token-Says#142]
Tried to test out the new feature in a fresh v12 world running PF2E system 6.0.4 with no result.

**Comment by hanna-greaves** [comment]
Hi @harrisog , thanks for letting me know you're having issues. Please could you let me know a bit more about how you configured your sayings? I have just double checked this myself by setting up a fresh world on foundry 12 / pf2e 6.0.4 and things seem to be working fine. 

Could you let me know what Foundry build you are on? (You can see this in the Game Settings tab)

Do you have any other modules running?

Below is my setup as an example. The Mangy Wolf token has a damage saying set up and responds to any damage by saying ouch
![image](https://github.com/user-attachments/assets/0f143531-b976-4081-a3b6-303d824825b9)
![image](https://github.com/user-attachments/assets/fb8411ae-b4f9-4b6e-b587-5a3b41518470)
<table>
<tr>
<td><img src='https://github.com/user-attachments/assets/cd4b4d06-68b7-4b5b-b6bb-627ec09bce5c'/></td>
<td><img src='https://github.com/user-attachments/assets/d74ad020-d485-44da-8ee9-e9eb3b00c0c9'/></td>
</tr>
</table>

![image](https://github.com/user-attachments/assets/0a42b373-898e-4f6c-878f-2c997a4d8d90)

**Comment by dannyice96** [comment]
Hi, sorry for hijacking this thread, but I am facing the same issues on Foundry /  PF2e 5.16.1

![image](https://github.com/user-attachments/assets/08da365b-607d-40e9-9b82-bed24dd93b44) 
![image](https://github.com/user-attachments/assets/c7dea52e-3611-484e-8372-e1e2ca2821ce)
![image](https://github.com/user-attachments/assets/a1296e92-3c30-4891-84b4-13a59b8559e0) 
![image](https://github.com/user-attachments/assets/4c565fbe-b5a5-43bc-92ca-c2c2e709aacb)
![image](https://github.com/user-attachments/assets/b6031bc3-63f7-46c1-b3aa-95c5e8d8defe)

Here is the console error thing which I assume will help
![image](https://github.com/user-attachments/assets/31528ed2-b9d4-4ae0-ab0f-63bb2b1588a9)
![image](https://github.com/user-attachments/assets/4d094ecc-e44b-46f5-a534-95de27138712)

Let me know if you would like the list of modules still, there's quite a few 😅 (81)

Again, sorry if this a super rude or anything. Let me know if you would prefer me opening a new issue post.

**Comment by hanna-greaves** [comment]
That's really helpful thank you @dannyice96, and sorry that you're having issues with the new feature! I will check out what's happening there and get an update out as soon as I'm able. Thanks again for the report :)

**Comment by hanna-greaves** [comment]
@dannyice96 @harrisog  I've just updated the module on Foundry, I'm hoping it should fix the issue you've both been seeing, please let me know if it does not and I can investigate further :)

**Comment by harrisog** [comment]
Thank you, this fixed the issue I was having

**Comment by dannyice96** [comment]
Works great for me now, thanks @hanna-greaves !  I'm not sure if it's the same for @harrisog though.

**Comment by hanna-greaves** [comment]
That's great news, thanks both for reporting the issue 🙏 I'm going to close this now but please let me know if  you have any more problems in the future.
