### ISSUE TITLE
[PF2E] Bugged dropdowns

### ISSUE THREAD

**Issue by harrisog** [hanna-greaves/Token-Says#145]
In the Configure Saying window, basics tab, the dropdown menus for Actor Type and (critically) Action Type are blank. These were functional for me recently so I suspect the issue is related to the recent 6.1 PF2e system release. 
![Screenshot 2024-07-22 195104](https://github.com/user-attachments/assets/89e05f4d-3560-4726-9619-f6109d001021)
>_Foundry V 12.239, PF2e System 6.1.1_

**Comment by hanna-greaves** [comment]
Thanks @harrisog I will investigate this asap

**Comment by hanna-greaves** [comment]
@harrisog this should be fixed in the latest release. Let me know if it you're still having issues

**Comment by harrisog** [comment]
That did the trick, thank you 🙏
